export const REPORTS_SECOES = {
  SUMARIO_EXECUTIVO: 'SUMARIO_EXECUTIVO',
  JORNADA_CLIENTE: 'JORNADA_CLIENTE',
  ANALISE_ESTOQUE: 'ANALISE_ESTOQUE_IMOBILIARIO',
  DESEMPENHO_VENDAS: 'DESEMPENHO_VENDAS',
  DESEMPENHO_LOCACOES: 'DESEMPENHO_LOCACOES',
} as const;

export const IMOVEIS_TIPOS = {
  APARTAMENTO: 'Apartamento',
  CASA: 'Casa',
  TERRENO: 'Terreno',
} as const;
