name: Deploy Node.js App (Docker on Linux Runner)

on:
  push:
    branches:
      - test-pedrão-ci-cd
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Run on Debian
    # Ajustado para as labels que apareceram no seu terminal
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Limpar container antigo
        run: |
          # Verifica se o container existe antes de tentar parar
          if [ "$(docker ps -aq -f name=backend-app)" ]; then
              echo "Parando e removendo container antigo..."
              docker stop backend-app
              docker rm backend-app
          fi

      - name: Build da Imagem Docker
        run: |
          # O Dockerfile usa node:22-slim, que é compatível com o seu Debian
          docker build -t backend-node-app:latest .

      - name: Iniciar o Container
        run: |
          docker run -d \
            --name backend-app \
            -p 8080:8080 \
            --restart always \
            backend-node-app:latest
          
          echo "Deploy realizado com sucesso no servidor Linux!"

      - name: Verificar Status
        run: |
          docker ps -f name=backend-app